# action.yml
name: 'Hola mundo'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id de la entrada
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id de la salida
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
